version: "3.9"
services:
  proxy:
    image: owasp/modsecurity-crs
    environment:
      PROXY: 1
      PROXYLOCATION: "http://cssdb:8080/"
    ports:
      - 8086:80
  cssdb:
    build: flask
    volumes:
      - cssdb_data:/data
  dbbuild:
    build: dbbuild
    volumes:
      - cssdb_data:/data
volumes:
  cssdb_data:
